### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by kolyshkin** [moby/sys#102]
Unless there are any objections from @moby/moby-maintainers, I am going to rename master to main in this repo in about a week.

Local repos need to be updated after that; github will provide clear instructions about it.

**Comment by cpuguy83** [comment]
Sounds great.

**Comment by thaJeztah** [comment]
no objections

**Comment by thaJeztah** [comment]
do you have access to the repo settings to do the rename, @kolyshkin ?

**Comment by samuelkarp** [comment]
Sounds great to me!

**Comment by yongtang** [comment]
+1 to me 👍

**Comment by kolyshkin** [comment]
> do you have access to the repo settings to do the rename, @kolyshkin ?

Looks like I do, yes.

**Comment by manugupt1** [comment]
This is an awesome change. Thanks

**Comment by thaJeztah** [comment]
I went ahead and renamed the branch:

<img width="498" alt="Screenshot 2022-02-01 at 10 21 18" src="https://user-images.githubusercontent.com/1804568/151942466-b243c607-3747-415e-b42e-f2fb1ad3718d.png">


Let me close this ticket 👍

**Comment by kolyshkin** [comment]
OK, here is what needs to be done locally:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

The above is per github recommendations. In addition, I also highly recommend
```
git remote prune origin
```
