### ISSUE TITLE
Requesting a new release for mountinfo

### ISSUE THREAD

**Issue by manugupt1** [moby/sys#110]
I need to update mountinfo for https://github.com/kubernetes/kubernetes/pull/109217 as all tests are following since: https://github.com/moby/sys/commit/925ece265955e861c1292597fe0da9dd1ed66668

Can I get a new release?

cc @kolyshkin @thaJeztah

**Comment by kolyshkin** [comment]
Let's say we hope to release it this week. Not much changes so easy to cut a release.

**Comment by kolyshkin** [comment]
https://github.com/moby/sys/releases/tag/mountinfo%2Fv0.6.1

(will do a new mount release, too)
