### ISSUE TITLE
Nominating Kazuyoshi Kato (@kzys) as maintainer for moby/sys

### ISSUE THREAD

**Issue by thaJeztah** [moby/sys#123]
I'm opening this as a ticket, as this repository (currently) doesn't have a MAINTAINERS file (code was extracted from moby/moby, and the list of maintainers for moby implicitly is also the list of maintainers for this code). I asked @kzys at some point if he would be interested on helping maintain this repo, but didn't follow-up after that (my bad!).

The modules in the moby/sys repository are used by various projects (moby, buildkit, containerd, runs). @kzys is a containerd maintainer, and has contributed to code in this repository, as well as integration of the code into containerd. I think @kzys would be a good addition as maintainer for this repository; more eyes is always good, and some changes (such as https://github.com/moby/sys/pull/121) relate to moving code in containerd (https://github.com/containerd/containerd/pull/7334), so having more containerd maintainers for reviews is (IMO) a good thing to have.

Let me know what you think!

@kolyshkin @AkihiroSuda @samuelkarp @cpuguy83 @tianon

**Comment by AkihiroSuda** [comment]
LGTM :+1:

**Comment by cpuguy83** [comment]
LGTM

**Comment by samuelkarp** [comment]
LGTM!

**Comment by kzys** [comment]
Thanks! Looks good to me :)

**Comment by thaJeztah** [comment]
🎉 🥳 thanks @kzys 

I created an @moby/moby-sys-maintainers team, and added existing maintainers and @kzys to that list (at least, you should have an invite).
