### ISSUE TITLE
is RecursiveUnmount needed?

### ISSUE THREAD

**Issue by kolyshkin** [moby/sys#21]
Today I was looking into RecursiveUnmount code and thought we can optimize it by adding the fast path, like this:

```diff
 // RecursiveUnmount unmounts the target and all mounts underneath, starting with
 // the deepsest mount first.
 func RecursiveUnmount(target string) error {
+       // Fast path: if we can unmount target, there are no submounts!
+       if err := unmount(target, 0); err == nil {
+               return nil
+       }
+
        mounts, err := mountinfo.GetMounts(mountinfo.PrefixFilter(target))
        if err != nil {
                return err
```

The idea is, if there are other mounts under `target`, we'll go the usual slow way, but if not, all it takes a single syscall.

When I read the umount(2) man page for the umphteen time, to confirm my gut feeling I should NOT use MNT_DETACH in the fast path, and found this gem:

> immediately disconnect the filesystem and  all  filesystems
> mounted below it from each other and from the mount table

This means that MNT_DETACH performs a recursive unmount. Since we do use MNT_DETACH from RecursiveUnmount anyway, it seems all of it, in its entirety, can be replaced by a single `umount(2)` with MNT_DETACH.

@cpuguy83 can you please shed some light on how you came with RecursiveUnmount in the first place? I tracked its inception down to PR  https://github.com/moby/moby/pull/31012 (https://github.com/moby/moby/pull/31012/commits/54dcbab25ea4771da303fa95e0c26f2d39487b49#diff-ce9e7d50400d88435b2be4f4cd9b7b23R61) but it's not very clear why it was added. I am surely very interested in your other input on this topic.

**Comment by cpuguy83** [comment]
The problem with `MNT_DETACH` is we can end up leaking data if there are leaked mounts... e.g. we try to remove a directory we did a lazy unmount of, it succeeds, but the reference is still held in another namespace so the data isn't actually gone.

The primary case we found for this issue was other system services, such as ntpd, get started with their own  mount ns and wind up holding onto mount references which docker made private and therefore unable to be unmounted fully, and as such the data never actually cleaned up.

As to why was `RecursiveUnount` created, indeed to battle some of this which was not fully understood at the time. Additionally there can technically be mounts that a container creates that we don't know about which get propagated to the host ns.

**Comment by kolyshkin** [comment]
Yep, I'm well aware of `MNT_DETACH` limitations, as well as the issues wrt making mounts that leaked to other mount namespaces private.

I guess, my ultimate question is, since

1) `umount(..., MNT_DETACH)` is in fact recursive, and
2) we're using this flag anyway pretty much everywhere (incluing `RecursiveUnmount`),

can we reimplement RecursiveUnmount like this:

```go
func RecursiveUnmount(target string) error {
                return unmount(target, mntDetach)
}
```
?

**Comment by kolyshkin** [comment]
or, since `Unmount` does exactly the same, just
```go
var RecursiveUnmount = Unmount
```

**Comment by kolyshkin** [comment]
Just tried creating a few real filesystems (ext4, btrfs, far, ntfs (over fuse), and xfs -- just in case this behavior is fs-specific) on loopback block devices, and mounting them in a matryoshka (Russian) doll fashion. Wrote something to all of them to make sure they are touched/used by the kernel.

A single call to `umount(path, MNT_DETACH)` unmounted all five of them, and all five loop devices became free.

In case some of these FS has users (I delibeately left a process running with PWD equal to one of the mounts), they are also unmounted just fine (as it is expected with MNT_DETACH), but the loop device holding this mount can't be dismantled (i.e. the device is in use) -- also as expected.

So, from this (very limited) testing it appears to be that RecursiveUnmount can indeed be replaced with a call to `umount(2)` will `MNT_DETACH` flag.

WDYT @cpuguy83 ?

**Comment by cpuguy83** [comment]
The issue comes from trying to remove the data from these mounts.
With MNT_DETATCH, removal is async and may never happen until all mount namespaces (which systemd itself creates depending on options such as `MountPropagation` and `PrivateTmp`) are shut down.

**Comment by kolyshkin** [comment]
I understand the gotchas of using MNT_DETACH.

My point is, we **already** do umounts with MNT_DETACH, so nothing will change with my proposal wrt `MNT_DETACH`. Here's the part of `RecursiveUmount` doing the unmount:

https://github.com/moby/sys/blob/95fd265abb1e7d346dd00882d49fd717d17317b8/mount/mount.go#L41

**Comment by cpuguy83** [comment]
I see. Yeah seems fine then.
GitHub <notifications@github.com> wrote:
“I understand the gotchas of using MNT_DETACH.

My point is, we already do umounts with MNT_DETACH, so nothing will change with my proposal wrt MNT_DETACH. Here's the part of RecursiveUmount doing the unmount:

https://github.com/moby/sys/blob/95fd265abb1e7d346dd00882d49fd717d17317b8/mount/mount.go#L41”

**Comment by cpuguy83** [comment]
I will say that the current function unmounts anything beneath the given path regardless if the target path is a mountpoint.

**Comment by kolyshkin** [comment]
> I will say that the current function unmounts anything beneath the given path regardless if the target path is a mountpoint.

That's right, but is this the intended behavior? I mean, did you, as the author, envisioned such a use case (when the argument is not a mount point), or is this just the side effect of the way it is implemented?

If this is intended behavior, there's nothing we can currently do to optimize things :(

If this is a side effect of the current implementation, we can apply optimizations proposed above.

**Comment by cpuguy83** [comment]
> If this is intended behavior, there's nothing we can currently do to optimize things :(

Sorry it seems like we've gotten off track here.

What you proposed at the top will give us the behavior that we have today as well as the optimization where if the root path is a mount we don't need to go any further.
If it is not a mount we'll get EINVAL and we can continue attempting to search for submounts.

Let's just make sure we aren't using this trying to use this on non-mountpoints except during shutdown or similar cases.

**Comment by kolyshkin** [comment]
> If it is not a mount we'll get EINVAL and we can continue attempting to search for submounts.

We won't, since `unmount` deliberately ignores EINVAL as "not mounted".

So yes, we can try calling `unix.Unmount(path, unix.MNT_DETACH)` and if it does not return any errors this means that path was a mount point, and the directory, and all the directories below, are no longer mounted.

Seems like a worthwhile optimization, glad we found it! PR is coming.
