### ISSUE TITLE
convert users to new names in mountinfo

### ISSUE THREAD

**Issue by kolyshkin** [moby/sys#42]
mountinfo v0.3.1 brought in some breaking changes (see #34, #41).

For the reference, the breaking changes are:
1. Some `Mountinfo` fields has been renamed:
 * `Fstype` -> `FSType`
 * `Opts` -> `Options`
 * `VfsOpts` -> `VFSOptions`
2. One function has been renamed:
* `FstypeFilter` -> `FSTypeFilter`

It's on us to make sure all the users have a smooth transition. 

So far:
 - [x] https://github.com/containers/storage/pull/727
 - [x] https://github.com/opencontainers/runc/pull/2626
 - [x] moby/sys/mount: https://github.com/moby/sys/pull/44
 - [x] https://github.com/moby/moby/pull/41458
 - [x] https://github.com/DataDog/datadog-agent/pull/6495

**Comment by kolyshkin** [comment]
@thaJeztah can you try updating moby/moby?

**Comment by thaJeztah** [comment]
Will do 👍

**Comment by kolyshkin** [comment]
OK we're done here
