### ISSUE TITLE
mount: Add test coverage for RecursiveUnmount

### ISSUE THREAD

**Issue by thaJeztah** [moby/sys#45]
While there's tests for functions _used_ by this function (`GetMounts()`, `Unmount()`), there's currently no test coverage for `RecursiveUnmount()`. We could use some test coverage for this function.

Opening this as a tracking issue, and adding the "help wanted" label, in case someone wants to work on this (please comment below if you want to work on this!)

/cc @kolyshkin

**Comment by kolyshkin** [comment]
This is partially addressed by #64.

**Comment by manugupt1** [comment]
@thaJeztah can we close this now?

**Comment by kolyshkin** [comment]
Yes, I think this is now addressed by #64 and #107.
