### ISSUE TITLE
RFC: tag mount/v0.2.0

### ISSUE THREAD

**Issue by thaJeztah** [moby/sys#57]
diff: https://github.com/moby/sys/compare/mount/v0.1.1...97292d92dc5e4a2b1891fcf8abf59294cfc33b1d

Release notes ~(if https://github.com/moby/sys/pull/56 is included)~;

## mount v0.2.0

Breaking changes:

- Remove stub-implementations for Windows for `Mount()`, `Unmount()`,
  `RecursiveUnmount()`, `MergeTmpfsOptions()` ([#31][1])

Fixes and improvements:

- `go.mod`: update github.com/moby/sys/mountinfo to [v0.4.0][2] ([#44][3], [#56][4])
- use `MNT_*` flags from golang.org/x/sys/unix on freebsd ([#36][5])
- add support for OpenBSD in addition to FreeBSD ([#32][6])
- fix package overview documentation not showing ([#43][7])
- `RecursiveUnmount()`: minor improvements ([#46][8])

Thanks to:

- Tobias Klauser

[1]: https://github.com/moby/sys/pull/31
[2]: https://github.com/moby/sys/releases/tag/mountinfo%2Fv0.4.0
[3]: https://github.com/moby/sys/pull/44
[4]: https://github.com/moby/sys/pull/56
[5]: https://github.com/moby/sys/pull/36
[6]: https://github.com/moby/sys/pull/32
[7]: https://github.com/moby/sys/pull/43
[8]: https://github.com/moby/sys/pull/46

**Comment by thaJeztah** [comment]
@kolyshkin @cpuguy83 PTAL

**Comment by kolyshkin** [comment]
Made some minor edits to the proposed changelog. Feel free to cut a release @thaJeztah

**Comment by thaJeztah** [comment]
Thanks! I was wondering (related to https://github.com/moby/sys/pull/56: update github.com/moby/sys/mountinfo to v0.4.0)

Would it be useful to add a `replace` rule in the `go.mod` that uses the _local_ code? Something like;

```
replace github.com/moby/sys/mountinfo => ../mountinfo
```

That way CI would always test against "tip" (and catch regressions/breaking changes early).

Alternatively, CI could create a copy and add that rule; I recently spotted that it's possible to use an alternative `go.mod` (which could be a separate step in CI: "verify mountinfo "tip");

```
-modfile file
	in module aware mode, read (and possibly write) an alternate go.mod
	file instead of the one in the module root directory. A file named
	"go.mod" must still be present in order to determine the module root
	directory, but it is not accessed. When -modfile is specified, an
	alternate go.sum file is also used: its path is derived from the
	-modfile flag by trimming the ".mod" extension and appending ".sum".
```

**Comment by thaJeztah** [comment]
Tagged v0.2.0; https://github.com/moby/sys/releases/tag/mount%2Fv0.2.0
